name: auction_app
description: 부동산 실거래가 & 경매 지도 앱

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.0
  firebase_core: ^3.12.0
  webview_flutter: ^4.10.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/kakao_map.html
    - assets/tax_knowledge/
    - icon.png
